version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ilsmind/vision-dashboard:latest
    ports:
      - "4000:3000"
    environment:
      NODE_ENV: production
      EMPR_TOKEN: ${EMPR_TOKEN}
      USERS_FILE_PATH: /run/secrets/users_json
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    secrets:
      - users_json

secrets:
  users_json:
    file: ./secret/users.json
